name: conjunto_residencial_app
description: Aplicación móvil para gestión de conjunto residencial Aralia de Castilla
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  # UI & Design
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0

  # State Management
  provider: ^6.1.1

  # Network & API
  http: ^1.1.2

  # Storage
  shared_preferences: ^2.2.2

  # Utils
  intl: ^0.19.0
  uuid: ^4.2.2

  # Charts & Graphs
  fl_chart: ^0.65.0

  # Image & File
  image_picker: ^1.0.5
  file_picker: ^6.1.1
  url_launcher: ^6.2.2

  # Calendar & Date
  table_calendar: ^3.0.9

  # UI Components
  flutter_speed_dial: ^7.0.0
  pull_to_refresh: ^2.0.0

  # Firebase & Notifications (temporalmente deshabilitado para web)
  # firebase_core: ^3.6.0
  # firebase_messaging: ^15.1.3
  flutter_local_notifications: ^18.0.1

  # QR Code
  qr_flutter: ^4.1.0
  mobile_scanner: ^3.5.2

  # Payments
  url_strategy: ^0.2.0

  # Signature
  signature: ^5.4.0

  # Video & Camera
  video_player: ^2.8.1
  camera: ^0.10.5+5

  # PDF & Excel
  pdf: ^3.10.7
  printing: ^5.11.1
  path_provider: ^2.1.1
  open_file: ^3.3.2
  excel: ^4.0.2

  # Animations
  lottie: ^2.7.0
  confetti: ^0.7.0

  # Service Locator
  get_it: ^7.6.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/images/espacios/
    - assets/images/logos/
    - assets/animations/